"""RLHF from scratch on DistilGPT2.

A from scratch reinforcement learning from human feedback stack: decoding,
supervised finetuning, LoRA adapters, reward modeling, PPO, and the
preference optimization family (DPO, IPO, KTO, ORPO, SimPO). See
README.md for an overview and docs/ for the architecture, design
tradeoffs, and results writeups.
"""
from .decoding import (
    load_distilgpt2_tokenizer,
    load_distilgpt2_model,
    set_pad_token_to_eos,
    generate_and_decode,
    greedy_decode,
    sample_with_temperature,
    top_k_filter,
    top_p_filter,
    build_eval_prompt_set,
    generate_completions,
    stream_tokens,
    apply_stop_tokens,
    chat,
)
from .data import (
    build_synthetic_instruction_dataset,
    format_example,
    apply_template,
    tokenize_example,
    build_labels,
    mask_prompt_labels,
    pad_batch,
    make_attention_mask,
    collate_lm_batch,
    iterate_minibatches,
    train_val_split,
    build_synthetic_preference_dataset,
    format_preference,
)
from .optim import (
    adamw_update,
    linear_warmup_schedule,
    clip_grad_norm,
    accumulate_gradients,
)
from .sft import (
    shift_logits_and_labels,
    cross_entropy_loss,
    sft_train_step,
    evaluate_loss,
)
from .lora import (
    lora_delta,
    lora_linear_forward,
    init_lora_weights,
    freeze_base_params,
    count_trainable_params,
    merge_lora,
)
from .reward_model import (
    reward_head_forward,
    pairwise_reward_loss,
    reward_bce_loss,
    pairwise_accuracy,
    reward_train_step,
    score_with_reward,
    win_rate,
)
from .ppo import (
    sequence_logprob,
    per_token_kl,
    compute_returns,
    gae_advantages,
    policy_ratio,
    clipped_surrogate,
    value_function_loss,
    entropy_bonus,
    ppo_loss,
    kl_penalized_reward,
    batch_sequence_logprob,
)
from .preference_optimization import (
    dpo_logratios,
    dpo_ref_logratios,
    dpo_loss,
    ipo_loss,
    kto_loss,
    orpo_loss,
    simpo_loss,
)

__all__ = [
    "load_distilgpt2_tokenizer",
    "load_distilgpt2_model",
    "set_pad_token_to_eos",
    "generate_and_decode",
    "greedy_decode",
    "sample_with_temperature",
    "top_k_filter",
    "top_p_filter",
    "build_eval_prompt_set",
    "generate_completions",
    "stream_tokens",
    "apply_stop_tokens",
    "chat",
    "build_synthetic_instruction_dataset",
    "format_example",
    "apply_template",
    "tokenize_example",
    "build_labels",
    "mask_prompt_labels",
    "pad_batch",
    "make_attention_mask",
    "collate_lm_batch",
    "iterate_minibatches",
    "train_val_split",
    "build_synthetic_preference_dataset",
    "format_preference",
    "adamw_update",
    "linear_warmup_schedule",
    "clip_grad_norm",
    "accumulate_gradients",
    "shift_logits_and_labels",
    "cross_entropy_loss",
    "sft_train_step",
    "evaluate_loss",
    "lora_delta",
    "lora_linear_forward",
    "init_lora_weights",
    "freeze_base_params",
    "count_trainable_params",
    "merge_lora",
    "reward_head_forward",
    "pairwise_reward_loss",
    "reward_bce_loss",
    "pairwise_accuracy",
    "reward_train_step",
    "score_with_reward",
    "win_rate",
    "sequence_logprob",
    "per_token_kl",
    "compute_returns",
    "gae_advantages",
    "policy_ratio",
    "clipped_surrogate",
    "value_function_loss",
    "entropy_bonus",
    "ppo_loss",
    "kl_penalized_reward",
    "batch_sequence_logprob",
    "dpo_logratios",
    "dpo_ref_logratios",
    "dpo_loss",
    "ipo_loss",
    "kto_loss",
    "orpo_loss",
    "simpo_loss",
]
